name: Build and Release Custom Linter

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.3"

            - name: Install dependencies
              run: go mod tidy

            - name: Build the linter
              run: go build -v -o safelint ./cmd/safelint

            - name: Upload release assets
              uses: softprops/action-gh-release@v2
              with:
                  files: safelint
