name: Build and Release Custom Linter

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: "1.22.3"

            - name: Install dependencies
              run: go mod tidy

            - name: Build the linter
              run: go build -o safelint ./cmd/safelint

            - name: Upload release assets
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./safelint
                  asset_name: safelint
                  asset_content_type: application/octet-stream
